services:
  networking_service:
    image: networking_service:latest
    build:
      context: .
      dockerfile: networking_service/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: networking_service
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "9000:9000"  # gRPC/RPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web_service:
    image: web_service:latest
    build:
      context: .
      dockerfile: web_service/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: web_service
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "9001:9001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9001
      - NETWORKING_SERVICE_URL=http://networking_service:9000
      - ConnectionStrings__DefaultConnection=${DBCONNECTION}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16